#spring.application.name=api-gateway
#server.port=8087
#
## CORS
#spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true
#spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
#spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
#spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
#spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true
#
## ROUTE
#spring.cloud.gateway.server.webflux.routes[0].id=auth-service
#spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
#spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.application.name=api-gateway
server.port=8087

# ================= CORS =================
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true

# ================= AUTH SERVICE =================
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# ================= MESSAGE SERVICE =================
spring.cloud.gateway.server.webflux.routes[1].id=message-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/messages/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/messages/(?<segment>.*), /api/messages/${segment}

# ================= MEDIA SERVICE =================
spring.cloud.gateway.server.webflux.routes[2].id=media-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8086
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/media/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=RewritePath=/media/(?<segment>.*), /api/media/${segment}

# ================= WEBSOCKET (OPTIONAL) =================
spring.cloud.gateway.server.webflux.routes[3].id=ws-service
spring.cloud.gateway.server.webflux.routes[3].uri=ws://localhost:8083
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/ws/**