spring.application.name=eureka-service

server.port=${PORT:8761}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.server.wait-time-in-ms-when-sync-empty=0
eureka.server.enable-self-preservation=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always